
name: DailyBuild-Deploy
on:
  schedule:
    - cron:  '0 0,13 * * *'
  workflow_dispatch:
jobs:
  DailyBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    env:
     GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
     SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
     SLACK_CHANNEL: '#devops'
     TG_TOKEN: ${{ secrets.MCLOUD_TELEGRAM_TOKEN }}
     GH_TOKEN: ${{ secrets.MPROJECT_GH_TOKEN }}
             
    steps:          
      - name: Daily Run
        run: |
          curl "https://api.render.com/deploy/srv-cf1te994reb5o43ft240?key=kAAvKH4lSsA"       