
name: mCloud Ansible
on:
#   schedule:
#     - cron:  '1 4 * * 1-5'
  workflow_dispatch:
    inputs:
      ansible_cmd:
        description: 'Your Project Name'
        default: 'jenkins.yml -t base'
        
jobs:
  mCloud-ansible:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
     GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
     #ANSIBLE_HOST_KEY_CHECKING: False
     ANSIBLE_CONFIG: "${GITHUB_WORKSPACE}/mcloud-ansible/inventory/ansible.cfg"
     ANSIBLE_ROLES_PATH: ${GITHUB_WORKSPACE}/mcloud-ansible/playbook/roles:~/.ansible/roles
     ANSIBLE_WORKING_DIR: mcloud-ansible/playbook
     ANSIBLE_CMD: ${{ github.event.inputs.ansible_cmd || 'lemp.yml -t base' }}
     SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
     SLACK_CHANNEL: '#devops'
     ANSIBLE_LOG_FOLDER: ${GITHUB_WORKSPACE}/ansible
     
             
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: info 
        run: |
          ansible --version
          /opt/pipx/venvs/ansible-core/bin/python -m pip install prettytable jmespath
          sudo curl -sL https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack -o /usr/bin/mslack
          sudo chmod +x /usr/bin/mslack
  
      - name: mproject clone ${{ env.ANSIBLE_WORKING_DIR }}
        run: |
          git clone -b master git@bitbucket.org:devopsexpert/mcloud-ansible.git ${GITHUB_WORKSPACE}/mcloud-ansible
          
      - name: Run ansible playbook
        working-directory: ${{ env.ANSIBLE_WORKING_DIR }}
        run: |
           if [[ ! -f ${ANSIBLE_INVENTORY} ]]; then
             export ANSIBLE_INVENTORY="/etc/ansible/hosts"
             export TARGET_HOST="127.0.0.1"
             export ANSIBLE_STDOUT_CALLBACK=yaml
           fi 
           build_url=https://github.com/HarryTheDevOpsGuy/mproject/actions/runs/${{ github.run_id }}
           mslack chat send --title "${GITHUB_RUN_NUMBER} - Started Pipeline -> <${build_url}|${GITHUB_JOB}> By ${{ github.actor }}" --text "*Event :* \`$GITHUB_EVENT_NAME\`\n*Triggered :* \`${{ github.actor }}\`\n*Target Infra:* \`${TARGET_HOST}\`" --channel "${SLACK_CHANNEL}" --color good --filter '.file.url_private' > /dev/null 2>&1
           ansible-galaxy install -r ${GITHUB_WORKSPACE}/mcloud-ansible/playbook/requirements.yml
           echo "ansible-playbook -e 'target_host=127.0.0.1' ${ANSIBLE_CMD}"
           ansible-playbook -e "target_host=127.0.0.1" ${ANSIBLE_CMD}
           
         
